#!/bin/sh
picom &
feh --bg-fill /etc/nixos/wallpapers/monte.jpg &
polybar &
emote &
corectrl &
dunst &

bspc monitor -d 1 2 3 4 5
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width 6
bspc config normal_border_color "#1e1e2e"
bspc config focused_border_color "#f38ba8"
bspc config borderless_monocle true

bspc rule -a Emacs state=tiled
bspc rule -a Plank manage=on border=off locked=on focus=off follow=off

bspc config window_gap 10
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config gapless_monocle true

bspc config single_monocle false
bspc config split_ratio 0.50

bspc config focus_follows_pointer false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_modifier mod4
